service: lambda-calculator
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  - ${file(./calculateServerlessYML/calculate.yml)}
  - ${file(./jwtTokenGeneratorServerlessYML/jwtTokenGenerator.yml)}
  - ${file(./calCServerlessYML/calC.yml)}
  - ${file(./authServerlessYML/authorizer.yml)}